#ABIR SITE DO CLOCKIFY

#FAZER LOGIN

#EM MENU CLICK EM REPORTS

#CLICK EM DETAILED

#APLICA O FILTRO DO MêS ANTERIOR (21) ATÉ O MêS ATUAL (20)

#CLICK EM "EXPORT" E DEPOIS "SAVE AS A PDF"

#RENOMEAR ARQUIVO COM O NOME>: "..."

def run():
    pass