def run():
    #ACESSAR https://iss.fortaleza.ce.gov.br/grpfor/login.seam

    #PREENCHER CPF COM AS CREDENCIAIS DO ENV
    #PREENCHER PASSWORD COM AS CREDENCIAIS DO ENV
    #NA PARTE DO "CAPTCHA" EXIBIR UMA TELA PARA PARA PESSOA PREENCHER O CAPTCAH ( PROCURAR UMA SOLUÇÃO MELHOR DEPOIS)
    #CLICK BTN ENTRAR

    #CLICK EMITIR NFS

    #EXIBIR TELA PARA PREENCHER CNPJ E VALOR DO SERVIÇO, SENDO QUE O CNPJ DO CLIENTE SE JÁ ESTIVER NO PREENCHIDO EM CONFIG,
    #JÁ VEM PREENCHIDO AQUI

    #SELECIONAR A OPÇÃO "CNPJ" NO CHECKBOX
    #DIGITAR O "CPNPJ_CLIENT" E SELECIONAR O CLIENTE

    #CLICK NA OUTRA ABA "SERVIÇO"

    #SELECIONA O CNAE "TREINAMENTO EM INFORMÁTICA"

    #ESCREVER UMA DESCRIÇÃO NO SERVIÇO "SERVIÇOS PRESTADOS REFERENTE AO MÊS DE {} PARA FORTICS."

    #PREENCHER VALOR DO SERVIÇO

    #CLICKAR EM "VALIDAR CAMPOS OBRIATÓRIOS"

    #PODE PARAR AQUI E NÃO EMITIR A NOTA...
    print('Rodando Script')